apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: donation-dev
  name: donation-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: donation-dev
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/donation-default: "true"
        io.kompose.service: donation-dev
    spec:
      containers:
        - env:
            - name: AZURE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: content-config
                  key: AZURE_CONNECTION
          image: zanzibarinh/donation-dev:{{.Values.version}}
          name: donation-dev
          resources: {}
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: donation-dev{{.Values.environment}}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: donation-dev{{.Values.environment}} 
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status: {}
